Small change for performance optimization.
String.format() is a very expensive call compare to regular '+'.
I wrote a small program which did benchmarking for 10K property path creation.

java testStringPerformance
StringFormat = 107 millisecond
String Concat = 41 millisecond
String Builder = 5 millisecond
String Replace = 22 millisecond

So using StringBuilder for any path which has more than 2 variables and String concat for just 1 variable.

Testing done:
Local test completed:
[ERROR] Failures:
[ERROR]   TestNoThrottleDisabledPartitions.testDisablingTopStateReplicaByDisablingInstance:98 expected:<false> but was:<true>
[ERROR]   TestNoThrottleDisabledPartitions.testNoThrottleOnDisabledInstance:231->setupEnvironment:317->setupCluster:436 » ZkClient
[ERROR]   TestP2PNoDuplicatedMessage.testP2PStateTransitionEnabled:180 expected:<true> but was:<false>
[ERROR]   TestRoutingTableProvider.testCustomizedViewCorrectConstructor:315 expected:<true> but was:<false>
[ERROR]   TestResourceThreadpoolSize.testBatchMessageThreadPoolSize:206 expected:<true> but was:<false>
[ERROR] Tests run: 1326, Failures: 5, Errors: 0, Skipped: 1