Fix CI testcase failure.
We have seen afterClass(org.apache.helix.integration.multizk.TestMultiZkConnectionConfig) failing.
The possible cause is that TestMultiZkHelixJavaApis re-initializes the _zkClient connection.
Parent class TestMultiZkConnectionConfig already creates _zkClient in beforeClass().

So it is possible that we have dangling zkclient which in the afterClass cleanup causes the failure.

Testing Done:
[ERROR] Failures:
[ERROR]   TestNoThrottleDisabledPartitions.testDisablingTopStateReplicaByDisablingInstance:98 expected:<false> but was:<true>
[ERROR]   TestNoThrottleDisabledPartitions.testNoThrottleOnDisabledInstance:231->setupEnvironment:317->setupCluster:436 » ZkClient
[ERROR]   TestRecurringJobQueue.stopDeleteJobAndResumeRecurrentQueue:123 » Helix Failed ...
[ERROR]   TestRecurringJobQueue.testDeletingRecurrentQueueWithHistory:298 expected:<true> but was:<false>
[ERROR]   TestClusterStatusMonitorLifecycle.testClusterStatusMonitorLifecycle:297 Remaining MBeans: