Fix for Failed-CI test: testSubMessageFailed
The test has sleep() and then expects the async update for
states to be updated.

Replaced Assert with verify().

Testing done:
[ERROR] Failures:
[ERROR]   TestNoThrottleDisabledPartitions.testDisablingTopStateReplicaByDisablingInstance:98 expected:<false> but was:<true>
[ERROR]   TestClusterMaintenanceMode.testMaintenanceHistory:412 expected:<EXIT> but was:<ENTER>
[ERROR]   TestP2PNoDuplicatedMessage.testP2PStateTransitionEnabled:180 expected:<true> but was:<false>
[ERROR] Tests run: 1326, Failures: 3, Errors: 0, Skipped: 0

The test failed with following erorr message:
(org.apache.helix.integration.TestBatchMessageHandling