Fix CI Failure: TestClusterAggregateMetrics.testAggregateMetrics
Failure is related to missing-top-state metrics being not reported immediately
after external state has been updated.
As we know that pipeline runs multiple times and it is possible that pipeline
with missing-top-state is not yet completed.

Instead of immediately checking, do it using Verify() helper method.

Testing done:
mvn -q test
[ERROR] Failures:
[ERROR]   TestNoThrottleDisabledPartitions.testDisablingTopStateReplicaByDisablingInstance:98 expected:<false> but was:<true>
[ERROR]   TestNoThrottleDisabledPartitions.testNoThrottleOnDisabledInstance:231->setupEnvironment:317->setupCluster:436 » ZkClient
[ERROR]   TestP2PNoDuplicatedMessage.testP2PStateTransitionEnabled:180 expected:<true> but was:<false>
[ERROR]   TestWagedRebalanceFaultZone.testAddZone:288 expected:<true> but was:<false>
[ERROR]   TestRecurringJobQueue.testDeletingRecurrentQueueWithHistory:298 expected:<true> but was:<false>
[ERROR] Tests run: 1335, Failures: 5, Errors: 0, Skipped: 0