Upgrade the HttpClient version to latest 4.5.14 across all 3 components
We have a bug / review out by depenency-bot which suggested to bump up version due to vulnerability in 4.5.8 version.
So trying to be consistent and use the same for all 3 places where we use.

Testing done:
[ERROR] Failures:
[ERROR]   TestNoThrottleDisabledPartitions.testDisablingTopStateReplicaByDisablingInstance:98 expected:<false> but was:<true>
[ERROR]   TestNoThrottleDisabledPartitions.testNoThrottleOnDisabledInstance:231->setupEnvironment:317->setupCluster:436 » ZkClient
[ERROR]   TestNoThrottleDisabledPartitions.testNoThrottleOnDisabledPartition:263->setupEnvironment:317->setupCluster:436 » ZkClient
[ERROR]   TestZkConnectionLost.testLostZkConnection:179 » Helix Workflow testLostZkConne...
[ERROR]   TestClusterMaintenanceMode.testMaintenanceHistory:412 expected:<EXIT> but was:<ENTER>
[ERROR]   TestP2PNoDuplicatedMessage.testP2PStateTransitionEnabled:180 expected:<true> but was:<false>
[ERROR]   TestRecurringJobQueue.testDeletingRecurrentQueueWithHistory:298 expected:<true> but was:<false>
[ERROR]   TestResourceThreadpoolSize.testBatchMessageThreadPoolSize:206 expected:<true> but was:<false>
[ERROR] Tests run: 1326, Failures: 8, Errors: 0, Skipped: 0