Small bug fixes related to ZK disconnect. We added the fix where we retry with exponential backoff. There are some new failures in the test because tests have become underministic wrt time to wait. So let us remove randomness by explicitly waiting for thread to join. Also, retryCount should start with 0 and then increment it. This is the same behavior in other Exponential backoff call in other ZK API.
Testing Done: mvn test (in zookeeper-api as well as helix-core)
[ERROR] Failures:
[ERROR]   TestNoThrottleDisabledPartitions.testDisablingTopStateReplicaByDisablingInstance:98 expected:<false> but was:<true>
[ERROR]   TestNoThrottleDisabledPartitions.testNoThrottleOnDisabledInstance:231->setupEnvironment:317->setupCluster:436 » ZkClient
[ERROR]   TestP2PNoDuplicatedMessage.testP2PStateTransitionEnabled:180 expected:<true> but was:<false>
[ERROR]   TestStateTransitionTimeout.testStateTransitionTimeOut:170 expected:<true> but was:<false>
[ERROR]   TestWagedRebalanceTopologyAware.testAddZone:112->TestWagedRebalanceFaultZone.testAddZone:288 expected:<true> but was:<false>
[ERROR] Tests run: 1326, Failures: 5, Errors: 0, Skipped: 0